import { Category, CardTemplate, CategoryId } from '../types';

// ─── Category Definitions ────────────────────────────────────
// Each category maps to a gender/age filter for smart gallery sorting
export const CATEGORIES: Category[] = [
  {
    id: 'mom_bday',
    label: "Mom's Birthday",
    emoji: '👩',
    color: '#E8497F',
    bgColor: '#FFF0F5',
    accentColor: '#FFD6E7',
    genderFilter: 'female',
    ageFilter: 'adult',
    description: 'Create a beautiful card for mom',
  },
  {
    id: 'dad_bday',
    label: "Dad's Birthday",
    emoji: '👨',
    color: '#3B6FD4',
    bgColor: '#EEF4FF',
    accentColor: '#C5DAFF',
    genderFilter: 'male',
    ageFilter: 'adult',
    description: 'Make dad feel special',
  },
  {
    id: 'friend_bday',
    label: "Friend's Birthday",
    emoji: '🎉',
    color: '#E8822A',
    bgColor: '#FFF5EB',
    accentColor: '#FFE0C2',
    genderFilter: 'any',
    ageFilter: 'any',
    description: 'Celebrate your bestie',
  },
  {
    id: 'anniversary',
    label: 'Anniversary',
    emoji: '💕',
    color: '#C44DBF',
    bgColor: '#FBF0FB',
    accentColor: '#F0D0EF',
    genderFilter: 'couple',
    ageFilter: 'adult',
    description: 'Celebrate love together',
  },
  {
    id: 'thank_you',
    label: 'Thank You',
    emoji: '🙏',
    color: '#2EA87E',
    bgColor: '#EEFBF5',
    accentColor: '#C0F0DC',
    genderFilter: 'any',
    ageFilter: 'any',
    description: 'Show your gratitude',
  },
  {
    id: 'congrats',
    label: 'Congrats',
    emoji: '🏆',
    color: '#D4A828',
    bgColor: '#FFFBEB',
    accentColor: '#FFEDB0',
    genderFilter: 'any',
    ageFilter: 'any',
    description: 'Celebrate their success',
  },
];

// ─── Card Templates ──────────────────────────────────────────
// 3 template variants per category — different gradients & decorations
export const CARD_TEMPLATES: Record<CategoryId, CardTemplate[]> = {
  mom_bday: [
    {
      id: 'mom_bday_1',
      categoryId: 'mom_bday',
      title: 'Happy Birthday, Mom!',
      subtitle: 'To the most wonderful woman in the world',
      gradientColors: ['#FFB6C1', '#FF69B4', '#E8497F'],
      decorEmojis: ['🌸', '💐', '🎂', '✨'],
      fontColor: '#FFFFFF',
      overlayOpacity: 0.15,
    },
    {
      id: 'mom_bday_2',
      categoryId: 'mom_bday',
      title: 'Happy Birthday, Mom!',
      subtitle: 'To the most wonderful woman in the world',
      gradientColors: ['#FCE4EC', '#F8BBD0', '#AD1457'],
      decorEmojis: ['🌷', '🎀', '🧁', '💖'],
      fontColor: '#FFFFFF',
      overlayOpacity: 0.18,
    },
    {
      id: 'mom_bday_3',
      categoryId: 'mom_bday',
      title: 'Happy Birthday, Mom!',
      subtitle: 'To the most wonderful woman in the world',
      gradientColors: ['#F3E5F5', '#CE93D8', '#6A1B9A'],
      decorEmojis: ['🌺', '🌹', '🎂', '💝'],
      fontColor: '#FFFFFF',
      overlayOpacity: 0.12,
    },
  ],
  dad_bday: [
    {
      id: 'dad_bday_1',
      categoryId: 'dad_bday',
      title: 'Happy Birthday, Dad!',
      subtitle: 'The greatest dad anyone could wish for',
      gradientColors: ['#667EEA', '#3B6FD4', '#1A3A6C'],
      decorEmojis: ['⭐', '🎁', '🎂', '🥳'],
      fontColor: '#FFFFFF',
      overlayOpacity: 0.12,
    },
    {
      id: 'dad_bday_2',
      categoryId: 'dad_bday',
      title: 'Happy Birthday, Dad!',
      subtitle: 'The greatest dad anyone could wish for',
      gradientColors: ['#E0E0E0', '#546E7A', '#263238'],
      decorEmojis: ['⚓', '🎩', '🥃', '🏆'],
      fontColor: '#FFFFFF',
      overlayOpacity: 0.1,
    },
    {
      id: 'dad_bday_3',
      categoryId: 'dad_bday',
      title: 'Happy Birthday, Dad!',
      subtitle: 'The greatest dad anyone could wish for',
      gradientColors: ['#A1C4FD', '#0288D1', '#01579B'],
      decorEmojis: ['🚗', '🎂', '🎉', '👔'],
      fontColor: '#FFFFFF',
      overlayOpacity: 0.13,
    },
  ],
  friend_bday: [
    {
      id: 'friend_bday_1',
      categoryId: 'friend_bday',
      title: 'Happy Birthday, Bestie!',
      subtitle: "Here's to another year of amazing memories",
      gradientColors: ['#F6D365', '#E8822A', '#C0392B'],
      decorEmojis: ['🎈', '🎊', '🍰', '🥂'],
      fontColor: '#FFFFFF',
      overlayOpacity: 0.1,
    },
    {
      id: 'friend_bday_2',
      categoryId: 'friend_bday',
      title: 'Happy Birthday, Bestie!',
      subtitle: "Here's to another year of amazing memories",
      gradientColors: ['#FFECD2', '#FF6F61', '#B71C1C'],
      decorEmojis: ['🎉', '🎁', '🥳', '🍾'],
      fontColor: '#FFFFFF',
      overlayOpacity: 0.12,
    },
    {
      id: 'friend_bday_3',
      categoryId: 'friend_bday',
      title: 'Happy Birthday, Bestie!',
      subtitle: "Here's to another year of amazing memories",
      gradientColors: ['#84FAB0', '#00BFA5', '#00695C'],
      decorEmojis: ['🌈', '🎂', '🍕', '🎶'],
      fontColor: '#FFFFFF',
      overlayOpacity: 0.1,
    },
  ],
  anniversary: [
    {
      id: 'anniversary_1',
      categoryId: 'anniversary',
      title: 'Happy Anniversary!',
      subtitle: 'Celebrating your beautiful journey together',
      gradientColors: ['#F093FB', '#C44DBF', '#7B2D8E'],
      decorEmojis: ['💕', '💍', '🥂', '✨'],
      fontColor: '#FFFFFF',
      overlayOpacity: 0.12,
    },
    {
      id: 'anniversary_2',
      categoryId: 'anniversary',
      title: 'Happy Anniversary!',
      subtitle: 'Celebrating your beautiful journey together',
      gradientColors: ['#FFDDE1', '#EE9CA7', '#880E4F'],
      decorEmojis: ['🌹', '💖', '🍷', '💐'],
      fontColor: '#FFFFFF',
      overlayOpacity: 0.14,
    },
    {
      id: 'anniversary_3',
      categoryId: 'anniversary',
      title: 'Happy Anniversary!',
      subtitle: 'Celebrating your beautiful journey together',
      gradientColors: ['#FDEFEF', '#D7263D', '#5C0011'],
      decorEmojis: ['❤️', '💍', '🕊️', '🎉'],
      fontColor: '#FFFFFF',
      overlayOpacity: 0.11,
    },
  ],
  thank_you: [
    {
      id: 'thank_you_1',
      categoryId: 'thank_you',
      title: 'Thank You!',
      subtitle: 'Your kindness means the world to me',
      gradientColors: ['#43E97B', '#2EA87E', '#1A6B50'],
      decorEmojis: ['🌟', '💚', '🙏', '🌿'],
      fontColor: '#FFFFFF',
      overlayOpacity: 0.1,
    },
    {
      id: 'thank_you_2',
      categoryId: 'thank_you',
      title: 'Thank You!',
      subtitle: 'Your kindness means the world to me',
      gradientColors: ['#E0F7FA', '#00ACC1', '#006064'],
      decorEmojis: ['💐', '🌸', '☘️', '✨'],
      fontColor: '#FFFFFF',
      overlayOpacity: 0.12,
    },
    {
      id: 'thank_you_3',
      categoryId: 'thank_you',
      title: 'Thank You!',
      subtitle: 'Your kindness means the world to me',
      gradientColors: ['#FFF8E1', '#FFB300', '#E65100'],
      decorEmojis: ['🌻', '🌼', '🙏', '💛'],
      fontColor: '#FFFFFF',
      overlayOpacity: 0.13,
    },
  ],
  congrats: [
    {
      id: 'congrats_1',
      categoryId: 'congrats',
      title: 'Congratulations!',
      subtitle: 'You deserve every bit of this success',
      gradientColors: ['#F7DC6F', '#D4A828', '#8B6914'],
      decorEmojis: ['🏆', '🎉', '⭐', '🥇'],
      fontColor: '#FFFFFF',
      overlayOpacity: 0.12,
    },
    {
      id: 'congrats_2',
      categoryId: 'congrats',
      title: 'Congratulations!',
      subtitle: 'You deserve every bit of this success',
      gradientColors: ['#E8F5E9', '#43A047', '#1B5E20'],
      decorEmojis: ['🎓', '🎊', '🍾', '🌟'],
      fontColor: '#FFFFFF',
      overlayOpacity: 0.11,
    },
    {
      id: 'congrats_3',
      categoryId: 'congrats',
      title: 'Congratulations!',
      subtitle: 'You deserve every bit of this success',
      gradientColors: ['#FFF3E0', '#FB8C00', '#BF360C'],
      decorEmojis: ['🚀', '🏅', '🎯', '🥂'],
      fontColor: '#FFFFFF',
      overlayOpacity: 0.13,
    },
  ],
};
